apiVersion: v1
kind: Service
metadata:
  name: postgres-app-service
  labels:
    name: postgres-app-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-app-deploy
    app: demo-voting-app
